#!/bin/bash

colors=($(cat ~/.cache/wal/colors))

bg=${colors[0]}
fg=${colors[7]}
bright_color=${colors[9]}

themes=("minimal.rasi" "pdfs.rasi" "emoji.rasi" "clipboard.rasi" "wallpaper.rasi")

for theme in "${themes[@]}"; do
    sed -i "s/text-color: .*;/text-color: $fg;/" ~/.config/rofi/mythemes/$theme

    sed -i "/element-text, element-icon {/,/}/ s/background-color: .*;/background-color: inherit;/" ~/.config/rofi/mythemes/$theme
    sed -i "/element-text, element-icon {/,/}/ s/text-color: .*;/text-color: inherit;/" ~/.config/rofi/mythemes/$theme

    sed -i "/element selected {/ { n; s/background-color: .*;/background-color: $bright_color;/ }" ~/.config/rofi/mythemes/$theme
done

