#!/bin/sh

CONFIG_FILE="$HOME/.config/hypr/hyprland.conf"

if [[ -f "$CONFIG_FILE" ]]; then
    if grep -q "layout = master" "$CONFIG_FILE"; then
        sed -i 's/layout = master/layout = dwindle/' "$CONFIG_FILE"
    elif grep -q "layout = dwindle" "$CONFIG_FILE"; then
        sed -i 's/layout = dwindle/layout = master/' "$CONFIG_FILE"
    else
        notify-send "Unknown layout"
        exit 1
    fi
    
    hyprctl reload
else
    notify-send "File not found!"
fi

